In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [ ]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [ ]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [ ]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [ ]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [ ]:
X_min = X.min()
X_max = X.max()
X_scaled = (X-X_min)/(X_max-X_min + 1e-8)

In [ ]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state = 43)

In [ ]:
model = keras.Sequential([
    layers.Input(shape = (X_train.shape[1],)),
    layers.Dense(8, activation='relu'),
    layers.Dense(1,activation = 'sigmoid')
])

In [ ]:
model.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
from sklearn.utils import validation
history = model.fit(
    X_train.values, y_train.values,
    validation_data = (X_test.values, y_test.values),
    epochs =  100, batch_size = 4, verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.9167 - loss: 0.5299 - val_accuracy: 0.7500 - val_loss: 0.6362
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.5292 - val_accuracy: 0.7500 - val_loss: 0.6358
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5290 - val_accuracy: 0.7500 - val_loss: 0.6353
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.5295 - val_accuracy: 0.7500 - val_loss: 0.6349
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.5253 - val_accuracy: 0.7500 - val_loss: 0.6343
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.5247 - val_accuracy: 0.7500 - val_loss: 0.6338
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5234 - val_accuracy: 0.7500 - val_loss: 0.6332
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.5229 - val_accuracy: 0.7500 - val_loss: 0.6326
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9167 - loss: 0.5219 - val_accuracy: 0.7500 - val_loss: 0.6321
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.9167 - loss: 0.5235 - val_accuracy: 0.7500 - val_loss: 0.6315
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9167 - loss: 0.5208 - val_accuracy: 0.7500 - val_loss: 0.6310
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9167 - loss: 0.5190 - val_accuracy: 0.7500 - val_loss: 0.6305
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.5174 - val_accuracy: 0.7500 - val_loss: 0.6299
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.5164 - val_accuracy: 0.7500 - val_loss: 0.6294
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.5155 - val_accuracy: 0.7500 - val_loss: 0.6287
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.9167 - loss: 0.5158 - val_accuracy: 0.7500 - val_loss: 0.6282
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.5138 - val_accuracy: 0.7500 - val_loss: 0.6276
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.5134 - val_accuracy: 0.7500 - val_loss: 0.6269
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9167 - loss: 0.5117 - val_accuracy: 0.7500 - val_loss: 0.6263
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8333 - loss: 0.5121 - val_accuracy: 0.7500 - val_loss: 0.6256
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.5100 - val_accuracy: 0.7500 - val_loss: 0.6249
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.5086 - val_accuracy: 0.7500 - val_loss: 0.6243
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.5087 - val_accuracy: 0.7500 - val_loss: 0.6237
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8333 - loss: 0.5079 - val_accuracy: 0.7500 - val_loss: 0.6230
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9167 - loss: 0.5057 - val_accuracy: 0.7500 - val_loss: 0.6224
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.5047 - val_accuracy: 0.7500 - val_loss: 0.6217
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9167 - loss: 0.5037 - val_accuracy: 0.7500 - val_loss: 0.6211
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9167 - loss: 0.5028 - val_accuracy: 0.7500 - val_loss: 0.6204
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.5017 - val_accuracy: 0.7500 - val_loss: 0.6198
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.5020 - val_accuracy: 0.7500 - val_loss: 0.6192
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.4998 - val_accuracy: 0.7500 - val_loss: 0.6185
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.4989 - val_accuracy: 0.7500 - val_loss: 0.6178
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.4981 - val_accuracy: 0.7500 - val_loss: 0.6172
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.4971 - val_accuracy: 0.7500 - val_loss: 0.6165
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8333 - loss: 0.4967 - val_accuracy: 0.7500 - val_loss: 0.6158
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.4954 - val_accuracy: 0.7500 - val_loss: 0.6151
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.4941 - val_accuracy: 0.7500 - val_loss: 0.6144
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.4936 - val_accuracy: 0.7500 - val_loss: 0.6137
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.4928 - val_accuracy: 0.7500 - val_loss: 0.6131
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8333 - loss: 0.4920 - val_accuracy: 0.7500 - val_loss: 0.6123
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.4922 - val_accuracy: 0.7500 - val_loss: 0.6117
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8333 - loss: 0.4910 - val_accuracy: 0.7500 - val_loss: 0.6110
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9167 - loss: 0.4883 - val_accuracy: 0.7500 - val_loss: 0.6103
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.4877 - val_accuracy: 0.7500 - val_loss: 0.6096
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.4865 - val_accuracy: 0.7500 - val_loss: 0.6090
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9167 - loss: 0.4864 - val_accuracy: 0.7500 - val_loss: 0.6083
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.4846 - val_accuracy: 0.7500 - val_loss: 0.6077
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8333 - loss: 0.4845 - val_accuracy: 0.7500 - val_loss: 0.6069
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.4826 - val_accuracy: 0.7500 - val_loss: 0.6063
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.4811 - val_accuracy: 0.7500 - val_loss: 0.6056
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9167 - loss: 0.4804 - val_accuracy: 0.7500 - val_loss: 0.6048
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.4793 - val_accuracy: 0.7500 - val_loss: 0.6041
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9167 - loss: 0.4783 - val_accuracy: 0.7500 - val_loss: 0.6035
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8333 - loss: 0.4785 - val_accuracy: 0.7500 - val_loss: 0.6027
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.4761 - val_accuracy: 0.7500 - val_loss: 0.6021
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.4762 - val_accuracy: 0.7500 - val_loss: 0.6015
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.4746 - val_accuracy: 0.7500 - val_loss: 0.6007
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8333 - loss: 0.4749 - val_accuracy: 0.7500 - val_loss: 0.6000
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8333 - loss: 0.4742 - val_accuracy: 0.7500 - val_loss: 0.5992
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.4716 - val_accuracy: 0.7500 - val_loss: 0.5985
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.4706 - val_accuracy: 0.7500 - val_loss: 0.5977
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.4698 - val_accuracy: 0.7500 - val_loss: 0.5971
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9167 - loss: 0.4686 - val_accuracy: 0.7500 - val_loss: 0.5965
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.4680 - val_accuracy: 0.7500 - val_loss: 0.5958
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.4678 - val_accuracy: 0.7500 - val_loss: 0.5951
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.4659 - val_accuracy: 0.7500 - val_loss: 0.5944
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9167 - loss: 0.4674 - val_accuracy: 0.7500 - val_loss: 0.5938
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.4642 - val_accuracy: 0.7500 - val_loss: 0.5930
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9167 - loss: 0.4635 - val_accuracy: 0.7500 - val_loss: 0.5921
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8333 - loss: 0.4634 - val_accuracy: 0.7500 - val_loss: 0.5912
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9167 - loss: 0.4619 - val_accuracy: 0.7500 - val_loss: 0.5905
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.4606 - val_accuracy: 0.7500 - val_loss: 0.5898
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9167 - loss: 0.4598 - val_accuracy: 1.0000 - val_loss: 0.5889
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.4605 - val_accuracy: 1.0000 - val_loss: 0.5883
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.4584 - val_accuracy: 1.0000 - val_loss: 0.5876
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9167 - loss: 0.4571 - val_accuracy: 1.0000 - val_loss: 0.5869
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.4562 - val_accuracy: 1.0000 - val_loss: 0.5862
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.4550 - val_accuracy: 1.0000 - val_loss: 0.5855
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.4543 - val_accuracy: 1.0000 - val_loss: 0.5848
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.9167 - loss: 0.4537 - val_accuracy: 1.0000 - val_loss: 0.5841
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.4524 - val_accuracy: 1.0000 - val_loss: 0.5834
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.9167 - loss: 0.4517 - val_accuracy: 1.0000 - val_loss: 0.5825
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9167 - loss: 0.4506 - val_accuracy: 1.0000 - val_loss: 0.5817
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.9167 - loss: 0.4505 - val_accuracy: 1.0000 - val_loss: 0.5810
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9167 - loss: 0.4491 - val_accuracy: 1.0000 - val_loss: 0.5802
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9167 - loss: 0.4481 - val_accuracy: 1.0000 - val_loss: 0.5797
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9167 - loss: 0.4481 - val_accuracy: 1.0000 - val_loss: 0.5792
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.9167 - loss: 0.4467 - val_accuracy: 1.0000 - val_loss: 0.5785
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9167 - loss: 0.4453 - val_accuracy: 1.0000 - val_loss: 0.5778
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9167 - loss: 0.4452 - val_accuracy: 1.0000 - val_loss: 0.5773
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9167 - loss: 0.4446 - val_accuracy: 1.0000 - val_loss: 0.5764
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.4448 - val_accuracy: 1.0000 - val_loss: 0.5759
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9167 - loss: 0.4422 - val_accuracy: 1.0000 - val_loss: 0.5751
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.4423 - val_accuracy: 1.0000 - val_loss: 0.5745
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.4422 - val_accuracy: 1.0000 - val_loss: 0.5739
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.4393 - val_accuracy: 1.0000 - val_loss: 0.5734
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9167 - loss: 0.4398 - val_accuracy: 1.0000 - val_loss: 0.5725
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.4380 - val_accuracy: 1.0000 - val_loss: 0.5720
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.4370 - val_accuracy: 1.0000 - val_loss: 0.5714
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.4373 - val_accuracy: 1.0000 - val_loss: 0.5708